version: "3.7"
services:
  caldera:
    build:
      context: .
      dockerfile: dockerfile
    image: ubuntu
    container_name: caldera1
    ports:
       - "8888:8888"
       - "80:80"
       - "49222:22"
       - "443:443"
    restart: always
    volumes:
        - "/opt/caldera/caldera-persistent-volum:/opt/caldera/caldera-persistent-volume"
